"""create_schedule_plans_and_labels_tables

Revision ID: d0c624e253c0
Revises: 498e1a1ef1e2
Create Date: 2025-11-06 08:51:55.871911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0c624e253c0'
down_revision: Union[str, Sequence[str], None] = '498e1a1ef1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_plan_labels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_plan_labels')),
    sa.UniqueConstraint('name', name=op.f('uq_schedule_plan_labels_name'))
    )
    op.create_index('ix_schedule_plan_labels_category', 'schedule_plan_labels', ['category'], unique=False)
    op.create_index('ix_schedule_plan_labels_name', 'schedule_plan_labels', ['name'], unique=False)
    op.create_table('schedule_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Lower number = higher priority'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_schedule_plans_channel_id_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_plans')),
    sa.UniqueConstraint('channel_id', 'start_date', 'end_date', name='uq_schedule_plans_channel_dates')
    )
    op.create_index('ix_schedule_plans_channel_id', 'schedule_plans', ['channel_id'], unique=False)
    op.create_index('ix_schedule_plans_dates', 'schedule_plans', ['start_date', 'end_date'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False, comment="Start time in 'HH:MM' format (schedule-time)"),
    sa.Column('duration', sa.Integer(), nullable=False, comment='Duration in minutes'),
    sa.Column('content_type', sa.String(length=50), nullable=False, comment="Type of content: 'series', 'asset', 'rule', 'random', 'virtual_package'"),
    sa.Column('content_ref', sa.Text(), nullable=False, comment='Content reference (UUID or JSON depending on content_type)'),
    sa.Column('label_id', sa.UUID(), nullable=True),
    sa.Column('episode_policy', sa.String(length=50), nullable=True, comment="Episode selection policy (e.g., 'sequential', 'seasonal')"),
    sa.Column('playback_rules', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='Additional playback rules and directives'),
    sa.Column('operator_intent', sa.Text(), nullable=True, comment='Operator-defined metadata describing programming intent'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_programs_channel_id_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['schedule_plan_labels.id'], name=op.f('fk_programs_label_id_schedule_plan_labels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['schedule_plans.id'], name=op.f('fk_programs_plan_id_schedule_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    op.create_index('ix_programs_channel_id', 'programs', ['channel_id'], unique=False)
    op.create_index('ix_programs_label_id', 'programs', ['label_id'], unique=False)
    op.create_index('ix_programs_plan_id', 'programs', ['plan_id'], unique=False)
    op.create_index('ix_programs_start_time', 'programs', ['plan_id', 'start_time'], unique=False)
    op.drop_index(op.f('ix_schedule_template_block_instances_block_id'), table_name='schedule_template_block_instances')
    op.drop_index(op.f('ix_schedule_template_block_instances_start_time'), table_name='schedule_template_block_instances')
    op.drop_index(op.f('ix_schedule_template_block_instances_template_id'), table_name='schedule_template_block_instances')
    op.drop_table('schedule_template_block_instances')
    op.drop_index(op.f('ix_schedule_template_blocks_name'), table_name='schedule_template_blocks')
    op.drop_table('schedule_template_blocks')
    op.drop_index(op.f('ix_schedule_templates_is_active'), table_name='schedule_templates')
    op.drop_index(op.f('ix_schedule_templates_name'), table_name='schedule_templates')
    op.drop_table('schedule_templates')
    op.drop_column('asset_editorial', 'created_at')
    op.drop_column('asset_editorial', 'updated_at')
    op.drop_column('asset_probed', 'created_at')
    op.drop_column('asset_probed', 'updated_at')
    op.drop_column('asset_relationships', 'created_at')
    op.drop_column('asset_relationships', 'updated_at')
    op.drop_column('asset_sidecar', 'created_at')
    op.drop_column('asset_sidecar', 'updated_at')
    op.drop_column('asset_station_ops', 'created_at')
    op.drop_column('asset_station_ops', 'updated_at')
    op.drop_index(op.f('ix_channels_slug'), table_name='channels')
    op.create_unique_constraint('ix_channels_slug', 'channels', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_channels_slug', 'channels', type_='unique')
    op.create_index(op.f('ix_channels_slug'), 'channels', ['slug'], unique=True)
    op.add_column('asset_station_ops', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('asset_station_ops', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('asset_sidecar', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('asset_sidecar', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('asset_relationships', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('asset_relationships', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('asset_probed', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('asset_probed', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('asset_editorial', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('asset_editorial', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_table('schedule_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_schedule_templates'),
    sa.UniqueConstraint('name', name='uq_schedule_templates_name', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_schedule_templates_name'), 'schedule_templates', ['name'], unique=False)
    op.create_index(op.f('ix_schedule_templates_is_active'), 'schedule_templates', ['is_active'], unique=False)
    op.create_table('schedule_template_blocks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rule_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_schedule_template_blocks_new'),
    sa.UniqueConstraint('name', name='uq_schedule_template_blocks_new_name', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_schedule_template_blocks_name'), 'schedule_template_blocks', ['name'], unique=False)
    op.create_table('schedule_template_block_instances',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('block_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['schedule_template_blocks.id'], name=op.f('fk_template_block_instances_block_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['schedule_templates.id'], name=op.f('fk_template_block_instances_template_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_template_block_instances'))
    )
    op.create_index(op.f('ix_schedule_template_block_instances_template_id'), 'schedule_template_block_instances', ['template_id'], unique=False)
    op.create_index(op.f('ix_schedule_template_block_instances_start_time'), 'schedule_template_block_instances', ['start_time'], unique=False)
    op.create_index(op.f('ix_schedule_template_block_instances_block_id'), 'schedule_template_block_instances', ['block_id'], unique=False)
    op.drop_index('ix_programs_start_time', table_name='programs')
    op.drop_index('ix_programs_plan_id', table_name='programs')
    op.drop_index('ix_programs_label_id', table_name='programs')
    op.drop_index('ix_programs_channel_id', table_name='programs')
    op.drop_table('programs')
    op.drop_index('ix_schedule_plans_dates', table_name='schedule_plans')
    op.drop_index('ix_schedule_plans_channel_id', table_name='schedule_plans')
    op.drop_table('schedule_plans')
    op.drop_index('ix_schedule_plan_labels_name', table_name='schedule_plan_labels')
    op.drop_index('ix_schedule_plan_labels_category', table_name='schedule_plan_labels')
    op.drop_table('schedule_plan_labels')
    # ### end Alembic commands ###
