"""apply naming conventions

Revision ID: c3c29fe1bf2c
Revises: f4c2bf916d30
Create Date: 2025-10-22 21:01:35.121657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c29fe1bf2c'
down_revision: Union[str, Sequence[str], None] = 'f4c2bf916d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The constraint already has the correct naming convention, so no need to recreate it
    # op.drop_constraint('sources_external_id_key', 'sources', type_='unique')
    # op.create_unique_constraint(op.f('uq_sources_external_id'), 'sources', ['external_id'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_sources_external_id'), 'sources', type_='unique')
    op.create_unique_constraint(op.f('sources_external_id_key'), 'sources', ['external_id'], postgresql_nulls_not_distinct=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    # ### end Alembic commands ###
