# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from retrovue import playout_pb2 as retrovue_dot_playout__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in retrovue/playout_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlayoutControlStub(object):
    """TODO: Add telemetry streaming RPC once engine exposes metrics.
    TODO: Introduce status subscription for real-time channel health updates.
    TODO: Define plan delta messages to minimize payload size during updates.

    PlayoutControl exposes lifecycle management operations for playout channels.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartChannel = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/StartChannel',
                request_serializer=retrovue_dot_playout__pb2.StartChannelRequest.SerializeToString,
                response_deserializer=retrovue_dot_playout__pb2.StartChannelResponse.FromString,
                _registered_method=True)
        self.UpdatePlan = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/UpdatePlan',
                request_serializer=retrovue_dot_playout__pb2.UpdatePlanRequest.SerializeToString,
                response_deserializer=retrovue_dot_playout__pb2.UpdatePlanResponse.FromString,
                _registered_method=True)
        self.StopChannel = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/StopChannel',
                request_serializer=retrovue_dot_playout__pb2.StopChannelRequest.SerializeToString,
                response_deserializer=retrovue_dot_playout__pb2.StopChannelResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/GetVersion',
                request_serializer=retrovue_dot_playout__pb2.ApiVersionRequest.SerializeToString,
                response_deserializer=retrovue_dot_playout__pb2.ApiVersion.FromString,
                _registered_method=True)


class PlayoutControlServicer(object):
    """TODO: Add telemetry streaming RPC once engine exposes metrics.
    TODO: Introduce status subscription for real-time channel health updates.
    TODO: Define plan delta messages to minimize payload size during updates.

    PlayoutControl exposes lifecycle management operations for playout channels.
    """

    def StartChannel(self, request, context):
        """StartChannel activates a playout channel with the provided plan on the target port.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlan(self, request, context):
        """UpdatePlan swaps the active plan for the given channel without interrupting playback.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopChannel(self, request, context):
        """StopChannel gracefully stops the active playout channel and releases resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """GetVersion returns the API version implemented by the playout engine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayoutControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.StartChannel,
                    request_deserializer=retrovue_dot_playout__pb2.StartChannelRequest.FromString,
                    response_serializer=retrovue_dot_playout__pb2.StartChannelResponse.SerializeToString,
            ),
            'UpdatePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlan,
                    request_deserializer=retrovue_dot_playout__pb2.UpdatePlanRequest.FromString,
                    response_serializer=retrovue_dot_playout__pb2.UpdatePlanResponse.SerializeToString,
            ),
            'StopChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.StopChannel,
                    request_deserializer=retrovue_dot_playout__pb2.StopChannelRequest.FromString,
                    response_serializer=retrovue_dot_playout__pb2.StopChannelResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=retrovue_dot_playout__pb2.ApiVersionRequest.FromString,
                    response_serializer=retrovue_dot_playout__pb2.ApiVersion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'retrovue.playout.PlayoutControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('retrovue.playout.PlayoutControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlayoutControl(object):
    """TODO: Add telemetry streaming RPC once engine exposes metrics.
    TODO: Introduce status subscription for real-time channel health updates.
    TODO: Define plan delta messages to minimize payload size during updates.

    PlayoutControl exposes lifecycle management operations for playout channels.
    """

    @staticmethod
    def StartChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/StartChannel',
            retrovue_dot_playout__pb2.StartChannelRequest.SerializeToString,
            retrovue_dot_playout__pb2.StartChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/UpdatePlan',
            retrovue_dot_playout__pb2.UpdatePlanRequest.SerializeToString,
            retrovue_dot_playout__pb2.UpdatePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/StopChannel',
            retrovue_dot_playout__pb2.StopChannelRequest.SerializeToString,
            retrovue_dot_playout__pb2.StopChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/GetVersion',
            retrovue_dot_playout__pb2.ApiVersionRequest.SerializeToString,
            retrovue_dot_playout__pb2.ApiVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
