# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retrovue/playout.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'retrovue/playout.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16retrovue/playout.proto\x12\x10retrovue.playout\x1a google/protobuf/descriptor.proto\"L\n\x13StartChannelRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x05\x12\x13\n\x0bplan_handle\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"8\n\x14StartChannelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"<\n\x11UpdatePlanRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x05\x12\x13\n\x0bplan_handle\x18\x02 \x01(\t\"6\n\x12UpdatePlanResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x12StopChannelRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x05\"7\n\x13StopChannelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x13\n\x11\x41piVersionRequest\"\x1d\n\nApiVersion\x12\x0f\n\x07version\x18\x01 \x01(\t2\xf5\x02\n\x0ePlayoutControl\x12]\n\x0cStartChannel\x12%.retrovue.playout.StartChannelRequest\x1a&.retrovue.playout.StartChannelResponse\x12W\n\nUpdatePlan\x12#.retrovue.playout.UpdatePlanRequest\x1a$.retrovue.playout.UpdatePlanResponse\x12Z\n\x0bStopChannel\x12$.retrovue.playout.StopChannelRequest\x1a%.retrovue.playout.StopChannelResponse\x12O\n\nGetVersion\x12#.retrovue.playout.ApiVersionRequest\x1a\x1c.retrovue.playout.ApiVersion:;\n\x13PLAYOUT_API_VERSION\x12\x1c.google.protobuf.FileOptions\x18\xd0\x86\x03 \x01(\tB\t\x82\xb5\x18\x05\x31.0.0b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retrovue.playout_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\202\265\030\0051.0.0'
  _globals['_STARTCHANNELREQUEST']._serialized_start=78
  _globals['_STARTCHANNELREQUEST']._serialized_end=154
  _globals['_STARTCHANNELRESPONSE']._serialized_start=156
  _globals['_STARTCHANNELRESPONSE']._serialized_end=212
  _globals['_UPDATEPLANREQUEST']._serialized_start=214
  _globals['_UPDATEPLANREQUEST']._serialized_end=274
  _globals['_UPDATEPLANRESPONSE']._serialized_start=276
  _globals['_UPDATEPLANRESPONSE']._serialized_end=330
  _globals['_STOPCHANNELREQUEST']._serialized_start=332
  _globals['_STOPCHANNELREQUEST']._serialized_end=372
  _globals['_STOPCHANNELRESPONSE']._serialized_start=374
  _globals['_STOPCHANNELRESPONSE']._serialized_end=429
  _globals['_APIVERSIONREQUEST']._serialized_start=431
  _globals['_APIVERSIONREQUEST']._serialized_end=450
  _globals['_APIVERSION']._serialized_start=452
  _globals['_APIVERSION']._serialized_end=481
  _globals['_PLAYOUTCONTROL']._serialized_start=484
  _globals['_PLAYOUTCONTROL']._serialized_end=857
# @@protoc_insertion_point(module_scope)
