# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import playout_pb2 as playout__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in playout_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlayoutControlStub(object):
    """TODO: Add telemetry streaming RPC once engine exposes metrics.
    TODO: Introduce status subscription for real-time channel health updates.
    TODO: Define plan delta messages to minimize payload size during updates.

    PlayoutControl exposes lifecycle management operations for playout channels.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartChannel = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/StartChannel',
                request_serializer=playout__pb2.StartChannelRequest.SerializeToString,
                response_deserializer=playout__pb2.StartChannelResponse.FromString,
                _registered_method=True)
        self.UpdatePlan = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/UpdatePlan',
                request_serializer=playout__pb2.UpdatePlanRequest.SerializeToString,
                response_deserializer=playout__pb2.UpdatePlanResponse.FromString,
                _registered_method=True)
        self.StopChannel = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/StopChannel',
                request_serializer=playout__pb2.StopChannelRequest.SerializeToString,
                response_deserializer=playout__pb2.StopChannelResponse.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/GetVersion',
                request_serializer=playout__pb2.ApiVersionRequest.SerializeToString,
                response_deserializer=playout__pb2.ApiVersion.FromString,
                _registered_method=True)
        self.LoadPreview = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/LoadPreview',
                request_serializer=playout__pb2.LoadPreviewRequest.SerializeToString,
                response_deserializer=playout__pb2.LoadPreviewResponse.FromString,
                _registered_method=True)
        self.SwitchToLive = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/SwitchToLive',
                request_serializer=playout__pb2.SwitchToLiveRequest.SerializeToString,
                response_deserializer=playout__pb2.SwitchToLiveResponse.FromString,
                _registered_method=True)
        self.AttachStream = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/AttachStream',
                request_serializer=playout__pb2.AttachStreamRequest.SerializeToString,
                response_deserializer=playout__pb2.AttachStreamResponse.FromString,
                _registered_method=True)
        self.DetachStream = channel.unary_unary(
                '/retrovue.playout.PlayoutControl/DetachStream',
                request_serializer=playout__pb2.DetachStreamRequest.SerializeToString,
                response_deserializer=playout__pb2.DetachStreamResponse.FromString,
                _registered_method=True)


class PlayoutControlServicer(object):
    """TODO: Add telemetry streaming RPC once engine exposes metrics.
    TODO: Introduce status subscription for real-time channel health updates.
    TODO: Define plan delta messages to minimize payload size during updates.

    PlayoutControl exposes lifecycle management operations for playout channels.
    """

    def StartChannel(self, request, context):
        """StartChannel activates a playout channel with the provided plan on the target port.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlan(self, request, context):
        """UpdatePlan swaps the active plan for the given channel without interrupting playback.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopChannel(self, request, context):
        """StopChannel gracefully stops the active playout channel and releases resources.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """GetVersion returns the API version implemented by the playout engine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadPreview(self, request, context):
        """Phase 9: Dual-producer control

        LoadPreview loads a new asset into the preview slot for the given channel.
        The engine will begin shadow decoding immediately, but will NOT switch live.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchToLive(self, request, context):
        """SwitchToLive promotes the current preview slot to the live slot atomically.
        Switching must be seamless: PTS continuity is preserved and the playout
        sink cannot detect the switch.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AttachStream(self, request, context):
        """Phase 8: byte transport attachment (Python owns stream sink, Air writes bytes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetachStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlayoutControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.StartChannel,
                    request_deserializer=playout__pb2.StartChannelRequest.FromString,
                    response_serializer=playout__pb2.StartChannelResponse.SerializeToString,
            ),
            'UpdatePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlan,
                    request_deserializer=playout__pb2.UpdatePlanRequest.FromString,
                    response_serializer=playout__pb2.UpdatePlanResponse.SerializeToString,
            ),
            'StopChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.StopChannel,
                    request_deserializer=playout__pb2.StopChannelRequest.FromString,
                    response_serializer=playout__pb2.StopChannelResponse.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=playout__pb2.ApiVersionRequest.FromString,
                    response_serializer=playout__pb2.ApiVersion.SerializeToString,
            ),
            'LoadPreview': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPreview,
                    request_deserializer=playout__pb2.LoadPreviewRequest.FromString,
                    response_serializer=playout__pb2.LoadPreviewResponse.SerializeToString,
            ),
            'SwitchToLive': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchToLive,
                    request_deserializer=playout__pb2.SwitchToLiveRequest.FromString,
                    response_serializer=playout__pb2.SwitchToLiveResponse.SerializeToString,
            ),
            'AttachStream': grpc.unary_unary_rpc_method_handler(
                    servicer.AttachStream,
                    request_deserializer=playout__pb2.AttachStreamRequest.FromString,
                    response_serializer=playout__pb2.AttachStreamResponse.SerializeToString,
            ),
            'DetachStream': grpc.unary_unary_rpc_method_handler(
                    servicer.DetachStream,
                    request_deserializer=playout__pb2.DetachStreamRequest.FromString,
                    response_serializer=playout__pb2.DetachStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'retrovue.playout.PlayoutControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('retrovue.playout.PlayoutControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlayoutControl(object):
    """TODO: Add telemetry streaming RPC once engine exposes metrics.
    TODO: Introduce status subscription for real-time channel health updates.
    TODO: Define plan delta messages to minimize payload size during updates.

    PlayoutControl exposes lifecycle management operations for playout channels.
    """

    @staticmethod
    def StartChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/StartChannel',
            playout__pb2.StartChannelRequest.SerializeToString,
            playout__pb2.StartChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/UpdatePlan',
            playout__pb2.UpdatePlanRequest.SerializeToString,
            playout__pb2.UpdatePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/StopChannel',
            playout__pb2.StopChannelRequest.SerializeToString,
            playout__pb2.StopChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/GetVersion',
            playout__pb2.ApiVersionRequest.SerializeToString,
            playout__pb2.ApiVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadPreview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/LoadPreview',
            playout__pb2.LoadPreviewRequest.SerializeToString,
            playout__pb2.LoadPreviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchToLive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/SwitchToLive',
            playout__pb2.SwitchToLiveRequest.SerializeToString,
            playout__pb2.SwitchToLiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AttachStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/AttachStream',
            playout__pb2.AttachStreamRequest.SerializeToString,
            playout__pb2.AttachStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetachStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrovue.playout.PlayoutControl/DetachStream',
            playout__pb2.DetachStreamRequest.SerializeToString,
            playout__pb2.DetachStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
