#!/bin/bash
# Generate gRPC stubs from the canonical proto at repo root.
# Run from repo root:  sh scripts/air/generate_proto.sh
# Or from scripts/air: sh generate_proto.sh
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# Canonical proto sources; C++ uses these via runtime/CMakeLists.txt
PROTO_DIR="${REPO_ROOT}/protos"
PLAYOUT_PROTO="${PROTO_DIR}/playout.proto"
EVIDENCE_PROTO="${PROTO_DIR}/execution_evidence_v1.proto"
# Python stubs: canonical location inside the retrovue package.
# protoc generates into $PYTHON_OUT/retrovue/ (from package retrovue;).
# The flatten step below moves stubs into $FINAL_PROTO_DIR.
PYTHON_OUT="${REPO_ROOT}/server/src"
FINAL_PROTO_DIR="${REPO_ROOT}/server/src/retrovue/proto"

if [ ! -f "$PLAYOUT_PROTO" ]; then
  echo "[ERROR] Proto not found: $PLAYOUT_PROTO" >&2
  exit 1
fi

mkdir -p "$PYTHON_OUT"

generate_python_stubs() {
  local proto_file="$1"
  local base_name
  base_name="$(basename "$proto_file" .proto)"

  python3 -m grpc_tools.protoc \
    -I "$PROTO_DIR" \
    --python_out="$PYTHON_OUT" \
    --grpc_python_out="$PYTHON_OUT" \
    "$proto_file"

  # Flatten nested package dirs into server/src/retrovue/proto/
  local found_files
  found_files=$(find "$PYTHON_OUT" -name "${base_name}_pb2.py" -o -name "${base_name}_pb2_grpc.py" 2>/dev/null)
  if [ -n "$found_files" ]; then
    mkdir -p "$FINAL_PROTO_DIR"
    for f in $found_files; do
      local fname
      fname="$(basename "$f")"
      if [ "$(dirname "$f")" != "$FINAL_PROTO_DIR" ]; then
        cp -f "$f" "${FINAL_PROTO_DIR}/$fname"
      fi
    done
    # Clean nested package subdirs left by protoc (e.g. retrovue/playout/)
    for subdir in "${PYTHON_OUT}"/retrovue/*/; do
      [ -d "$subdir" ] && [ "$(basename "$subdir")" != "__pycache__" ] && [ "$(basename "$subdir")" != "proto" ] && rm -rf "$subdir"
    done
    # Remove protoc-generated __init__.py in retrovue/ if it conflicts
    [ -f "${PYTHON_OUT}/retrovue/__init__.py" ] && rm -f "${PYTHON_OUT}/retrovue/__init__.py" 2>/dev/null || true
  fi

  echo "  Generated Python stubs for $base_name"
}

# Python (grpcio-tools):  pip install grpcio-tools
if command -v python3 >/dev/null 2>&1 && python3 -c "import grpc_tools" 2>/dev/null; then
  generate_python_stubs "$PLAYOUT_PROTO"
  if [ -f "$EVIDENCE_PROTO" ]; then
    generate_python_stubs "$EVIDENCE_PROTO"
  else
    echo "[WARN] Evidence proto not found: $EVIDENCE_PROTO (skipping)" >&2
  fi
  echo "Generated Python stubs in ${FINAL_PROTO_DIR}/"
else
  echo "[WARN] python3 + grpcio-tools not found; skip: pip install -r server/requirements.txt" >&2
fi

# C++ is generated by runtime CMake; no need to run protoc here.
echo "Canonical protos: $PROTO_DIR/*.proto"
echo "Python stubs:     $FINAL_PROTO_DIR/ (if grpcio-tools ran)"
echo "C++ stubs:        built by cmake in runtime/build (see runtime/CMakeLists.txt)"
