#!/bin/bash
# Generate gRPC stubs from the canonical proto at repo root.
# Run from repo root:  sh scripts/air/generate_proto.sh
# Or from scripts/air: sh generate_proto.sh
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# Single canonical source; C++ uses this via pkg/air/CMakeLists.txt
PROTO_FILE="${REPO_ROOT}/protos/playout.proto"
# Python stubs: one location consumed by Core
PYTHON_OUT="${REPO_ROOT}/pkg/core/core/proto"

if [ ! -f "$PROTO_FILE" ]; then
  echo "[ERROR] Proto not found: $PROTO_FILE" >&2
  exit 1
fi

PROTO_IMPORT_DIR="$(dirname "$PROTO_FILE")"
mkdir -p "$PYTHON_OUT"

# Python (grpcio-tools):  pip install grpcio-tools
if command -v python3 >/dev/null 2>&1 && python3 -c "import grpc_tools" 2>/dev/null; then
  python3 -m grpc_tools.protoc \
    -I "$PROTO_IMPORT_DIR" \
    --python_out="$PYTHON_OUT" \
    --grpc_python_out="$PYTHON_OUT" \
    "$PROTO_FILE"
  # Flatten so existing code can load from .../core/proto/retrovue/
  PLAYOUT_DIR="${PYTHON_OUT}/retrovue/playout"
  if [ -d "$PLAYOUT_DIR" ]; then
    cp -f "${PLAYOUT_DIR}"/*.py "${PYTHON_OUT}/retrovue/"
    rm -rf "$PLAYOUT_DIR"
  fi
  echo "Generated Python stubs in ${PYTHON_OUT}/retrovue/"
else
  echo "[WARN] python3 + grpcio-tools not found; skip: pip install -r pkg/core/requirements.txt" >&2
fi

# C++ is generated by pkg/air CMake; no need to run protoc here.
echo "Canonical proto: $PROTO_FILE"
echo "Python stubs:    $PYTHON_OUT/retrovue/ (if grpcio-tools ran)"
echo "C++ stubs:       built by cmake in pkg/air/build (see pkg/air/CMakeLists.txt)"
