#!/bin/bash
# Generate gRPC stubs from the canonical proto at repo root.
# Run from repo root:  sh scripts/air/generate_proto.sh
# Or from scripts/air: sh generate_proto.sh
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# Canonical proto sources; C++ uses these via pkg/air/CMakeLists.txt
PROTO_DIR="${REPO_ROOT}/protos"
PLAYOUT_PROTO="${PROTO_DIR}/playout.proto"
EVIDENCE_PROTO="${PROTO_DIR}/execution_evidence_v1.proto"
# Python stubs: one location consumed by Core
PYTHON_OUT="${REPO_ROOT}/pkg/core/core/proto"

if [ ! -f "$PLAYOUT_PROTO" ]; then
  echo "[ERROR] Proto not found: $PLAYOUT_PROTO" >&2
  exit 1
fi

mkdir -p "$PYTHON_OUT"

generate_python_stubs() {
  local proto_file="$1"
  local base_name
  base_name="$(basename "$proto_file" .proto)"

  python3 -m grpc_tools.protoc \
    -I "$PROTO_DIR" \
    --python_out="$PYTHON_OUT" \
    --grpc_python_out="$PYTHON_OUT" \
    "$proto_file"

  # Flatten nested package dirs so code can load from .../core/proto/retrovue/
  local nested_dir="${PYTHON_OUT}/retrovue"
  # protoc may create package subdirs; find and flatten generated files
  local found_files
  found_files=$(find "$PYTHON_OUT" -name "${base_name}_pb2.py" -o -name "${base_name}_pb2_grpc.py" 2>/dev/null)
  if [ -n "$found_files" ]; then
    mkdir -p "${PYTHON_OUT}/retrovue"
    for f in $found_files; do
      local fname
      fname="$(basename "$f")"
      if [ "$(dirname "$f")" != "${PYTHON_OUT}/retrovue" ]; then
        cp -f "$f" "${PYTHON_OUT}/retrovue/$fname"
      fi
    done
    # Clean nested package subdirs (e.g. retrovue/playout/, retrovue/evidence/)
    for subdir in "${PYTHON_OUT}"/retrovue/*/; do
      [ -d "$subdir" ] && [ "$(basename "$subdir")" != "__pycache__" ] && rm -rf "$subdir"
    done
  fi

  echo "  Generated Python stubs for $base_name"
}

# Python (grpcio-tools):  pip install grpcio-tools
if command -v python3 >/dev/null 2>&1 && python3 -c "import grpc_tools" 2>/dev/null; then
  generate_python_stubs "$PLAYOUT_PROTO"
  if [ -f "$EVIDENCE_PROTO" ]; then
    generate_python_stubs "$EVIDENCE_PROTO"
  else
    echo "[WARN] Evidence proto not found: $EVIDENCE_PROTO (skipping)" >&2
  fi
  echo "Generated Python stubs in ${PYTHON_OUT}/retrovue/"
else
  echo "[WARN] python3 + grpcio-tools not found; skip: pip install -r pkg/core/requirements.txt" >&2
fi

# C++ is generated by pkg/air CMake; no need to run protoc here.
echo "Canonical protos: $PROTO_DIR/*.proto"
echo "Python stubs:     $PYTHON_OUT/retrovue/ (if grpcio-tools ran)"
echo "C++ stubs:        built by cmake in pkg/air/build (see pkg/air/CMakeLists.txt)"
